### ISSUE TITLE
Semantic distance

### ISSUE THREAD

**Issue by WhimZig** [epfl-ada/ada-2023-project-amonavis#10]
Finding the semantic distance between two words, we need to decide on some method or methods to use.

Word2Vec is the one I mainly know about, and I know that there already exists versions with pretrained models: https://radimrehurek.com/gensim/models/word2vec.html

I was told that I should use transformers instead, but I'm not certain on how to use them for this when we're only treating one word. From what I understood, transformers are more useful when dealing with hole sentences, not with just one word. This article kinda goes over some ideas, but I haven't read it in detail: https://keras.io/examples/nlp/semantic_similarity_with_bert/

**Comment by carlos-collado** [comment]
we should create a dataframe or the info with the semantic distance between all the wikipedia articles

also from what I saw in Word2Vec, it only accepts single words, so it could be useful to look at the transformers that you mention.

**Comment by WhimZig** [comment]
Word2Vec does usually accept only single words, but sometimes it has extra things. For example, (I think) it would consider "New York" as one word and have a way of processing.

So I guess this does mean we need a way of transforming multiple word inputs...

An easy AF solution is also just to average out all of the words. I'd use this as a placeholder for now

**Comment by carlos-collado** [comment]
Yep, the problem I found is that Word2Vec has like a predefined list of words accepted, so maybe very obvious 2 words area accepted, but not a lot of articles such as "1980 eruption of Mount St. Helens".

I'm finally using this Bert model

model = BertModel.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

**Comment by carlos-collado** [comment]
I am able to compute all semantic distances well enough now. The only problem is that I wanted to create a matrix with the semantic distance between all articles but it is more than 10 million combinations so it takes an insane amount of time to compute (like just 0.1s per point but still cannot scale that much). I tried to use parallel computing but didn't work. Any ideas?

**Comment by WhimZig** [comment]
Please add it to one of the notebooks! I know I need to use this for myself, so it's helpful.

I don't think the distance between all is worth it tbh, I don't imagine we'll end up using that. If we need distance I think it makes sense to just calculate it on the fly, especially because we can't compare all words.

If you really wanna do the matrix, I think python already has some parallelization by default. There might be a way through lambda functions? But tbh I really think the only thing left is to just leave it overnight and maybe store the matrix

**Comment by carlos-collado** [comment]
okk I'll look at that. Just pushed this notebook!

**Comment by carlos-collado** [comment]
also, this calculates the opposite of semantic distance (i.e. semantic similarity).
