### ISSUE TITLE
Create a python environment?

### ISSUE THREAD

**Issue by WhimZig** [epfl-ada/ada-2023-project-amonavis#11]
We're going to be running multiple instances of this. It might be worthwhile to create a python environment and set it up to guarantee that we all have the same library and the same version of the libraries. I'm not sure how to set it up though, so we'd have to see how to organize this.

Might not be worth doing though, depends on if we start finding issues or not while building the initial versions of the code.

**Comment by WhimZig** [comment]
Related to this, I'm already having issues with the file path and adding files to different folders...

If I want to add the exploration notebooks to a separate folder and then run things, it fucks up part of the data reading. I can find simple-ish alternatives, but god damn it's a pain in the ass to do this properly...

**Comment by WhimZig** [comment]
We're already using a couple of extra packages, so yeah this is important AF to add so we know what's needed and what needs to be installed so that everything works properly

**Comment by DanielX278** [comment]
i never did it before but I can try: could it be enough to set it up from vs code and push the conda folder?

**Comment by carlos-collado** [comment]
Just added it (as venv, not conda).
