### ISSUE TITLE
Update readme file for second deliverable

### ISSUE THREAD

**Issue by WhimZig** [epfl-ada/ada-2023-project-amonavis#13]
Readme.md file containing the detailed project proposal (up to 1000 words). Your README.md should contain:

- Title
- Abstract: A 150 word description of the project idea and goals. What’s the motivation behind your project? What story would you like to tell, and why?
- Research Questions: A list of research questions you would like to address during the project.
- Proposed additional datasets (if any): List the additional dataset(s) you want to use (if any), and some ideas on how you expect to get, manage, process, and enrich it/them. Show us that you’ve read the docs and some examples, and that you have a clear idea on what to expect. Discuss data size and format if relevant. It is your responsibility to check that what you propose is feasible.
- Methods
- Proposed timeline
- Organization within the team: A list of internal milestones up until project Milestone P3.
- Questions for TAs (optional): Add here any questions you have for us related to the proposed project.

**Comment by DanielX278** [comment]
Uploaded the best abstract I came up with so far. I thought we can rename it _The Man and the Machine_, so we are not bounded to a "VS" kind of comparison (?)

**Comment by DanielX278** [comment]
closing this as the remaining concerns are already discussed in the thread carlos started (about the methods documentation)
